# Prepare datasets

Prepares the following datasets:
1. Adult
2. COMPAS
3. Communities and Crime
4. Motor Insurance

#### Libraries

In [1]:
import pandas as pd
from pandas import Series

from src.datasets import adult, compas, crime, motor, utils

#### Display options

In [2]:
pd.set_option('display.max_rows', None)

## Adult

#### Download the original Adult dataset

In [3]:
adult.download()

Preparing to download the original Adult dataset
Downloading from 'https://archive.ics.uci.edu/static/public/2/adult.zip'
Downloaded to 'data/datasets/adult/_original/adult.zip'

#### Process the original Adult dataset

In [4]:
try:
    dataset_name, X, s, _ = adult.process()
except FileExistsError as e:
    print(f"{e}; loading instead")
    dataset_name, X, s, _ = adult.load()

Loading the original Adult dataset from 'data/datasets/adult/_original/adult.zip'
  shape: (48842, 15)
Processing the original Adult dataset
  Dropping rows with NaN as per Le Quy (2022)
    shape: (45222, 15)
  Retaining only required attributes
    # non-sensitive attributes: 6
    sensitive attribute: 'age'
    shape: (45222, 7)
  Standardising continuous non-sensitive attributes
  One hot encoding categorical non-sensitive attributes
    shape: (45222, 28)
  Dropping original categorical non-sensitive attributes
    shape: (45222, 26)
Exporting the processed Adult dataset (adult) to 'data/datasets/adult/adult.csv'
╭───────────┬─────────────┬──────────────┬─────────────────────────────┬───────────────────────╮
│   dataset │   # objects │   # features │   # nonsensitive attributes │   sensitive attribute │
├───────────┼─────────────┼──────────────┼─────────────────────────────┼───────────────────────┤
│     adult │       45222 │           25 │                           6 │                   age │
╰───────────┴─────────────┴──────────────┴─────────────────────────────┴───────────────────────╯

#### Descriptive statistics of the non-sensitive attributes

In [5]:
X.apply(utils.describe_ser).T

                                   min        max      mean       std % missing
workclass:Federal-gov              0.0   0.707107  0.021985   0.12273       0.0
workclass:Local-gov                0.0   0.707107  0.048473   0.17868       0.0
workclass:Private                  0.0   0.707107    0.5208  0.311498       0.0
workclass:Self-emp-inc             0.0   0.707107  0.025737  0.132428       0.0
workclass:Self-emp-not-inc         0.0   0.707107  0.059356  0.196083       0.0
workclass:State-gov                0.0   0.707107  0.030428  0.143494       0.0
workclass:Without-pay              0.0   0.707107  0.000328  0.015234       0.0
education-num                 -3.57187   2.303909       0.0  1.000011       0.0
occupation:Adm-clerical            0.0   0.707107  0.086625  0.231842       0.0
occupation:Armed-Forces            0.0   0.707107  0.000219   0.01244       0.0
occupation:Craft-repair            0.0   0.707107  0.094131  0.240211       0.0
occupation:Exec-managerial         0.0   0.707107  0.093568  0.239601       0.0
occupation:Farming-fishing         0.0   0.707107  0.023142  0.125811       0.0
occupation:Handlers-cleaners       0.0   0.707107  0.031992  0.146965       0.0
occupation:Machine-op-inspct       0.0   0.707107   0.04644  0.175163       0.0
occupation:Other-service           0.0   0.707107   0.07518  0.217966       0.0
occupation:Priv-house-serv         0.0   0.707107  0.003628  0.050518       0.0
occupation:Prof-specialty          0.0   0.707107  0.093943  0.240008       0.0
occupation:Protective-serv         0.0   0.707107  0.015261  0.102755       0.0
occupation:Sales                   0.0   0.707107  0.084561  0.229444       0.0
occupation:Tech-support            0.0   0.707107  0.022204  0.123319       0.0
occupation:Transport-moving        0.0   0.707107  0.036214  0.155872       0.0
capital-gain                 -0.146733  13.175193      -0.0  1.000011       0.0
capital-loss                  -0.21878   10.53806       0.0  1.000011       0.0
hours-per-week               -3.326124   4.835527       0.0  1.000011       0.0

#### Descriptive statistics of the sensitive attribute

In [6]:
utils.describe_ser(ser=s).to_frame().T

    min max       mean       std % missing
age  17  90  38.547941  13.21787       0.0

## COMPAS

#### Download the original COMPAS dataset

In [7]:
compas.download()

Preparing to download the original COMPAS dataset
Downloading from 'https://github.com/propublica/compas-analysis/raw/master/compas-scores-two-years.csv'
Downloaded to 'data/datasets/compas/_original/compas-scores-two-years.csv'

#### Process the original COMPAS dataset

In [8]:
try:
    dataset_name, X, s, _ = compas.process()
except FileExistsError as e:
    print(f"{e}; loading instead")
    dataset_name, X, s, _ = compas.load()

Loading the original COMPAS dataset from 'data/datasets/compas/_original/compas-scores-two-years.csv'
  shape: (7214, 52)
Processing the original COMPAS dataset
  Filtering rows as per Angwin (2016)
    shape: (6172, 52)
  Retaining only required attributes
    # non-sensitive attributes: 7
    sensitive attribute: 'age'
    shape: (6172, 8)
  Standardising continuous non-sensitive attributes
  One hot encoding categorical non-sensitive attributes
    shape: (6172, 10)
  Dropping original categorical non-sensitive attributes
    shape: (6172, 9)
Exporting the processed COMPAS dataset (compas) to 'data/datasets/compas/compas.csv'
╭───────────┬─────────────┬──────────────┬─────────────────────────────┬───────────────────────╮
│   dataset │   # objects │   # features │   # nonsensitive attributes │   sensitive attribute │
├───────────┼─────────────┼──────────────┼─────────────────────────────┼───────────────────────┤
│    compas │        6172 │            8 │                           7 │                   age │
╰───────────┴─────────────┴──────────────┴─────────────────────────────┴───────────────────────╯

#### Descriptive statistics of the non-sensitive attributes

In [9]:
X.apply(utils.describe_ser).T

                        min        max      mean       std % missing
juv_fel_count     -0.127923  43.016305       0.0  1.000081       0.0
decile_score      -1.204023   1.965847       0.0  1.000081       0.0
juv_misd_count    -0.183232   25.93003      -0.0  1.000081       0.0
juv_other_count   -0.235102   18.88564       0.0  1.000081       0.0
priors_count      -0.684413   7.326743      -0.0  1.000081       0.0
c_charge_degree:F       0.0   0.707107  0.454831  0.338765       0.0
c_charge_degree:M       0.0   0.707107  0.252276  0.338765       0.0
v_decile_score    -1.061563   2.554978      -0.0  1.000081       0.0

#### Descriptive statistics of the sensitive attribute

In [10]:
utils.describe_ser(ser=s).to_frame().T

    min max       mean        std % missing
age  18  96  34.534511  11.730938       0.0

## Communities and Crime

#### Download the original Communities and Crime dataset

In [11]:
crime.download()

Preparing to download the original Communities and Crime dataset
Downloading from 'https://archive.ics.uci.edu/static/public/183/communities+and+crime.zip'
Downloaded to 'data/datasets/crime/_original/communities+and+crime.zip'

#### Process the original Communities and Crime dataset

In [12]:
try:
    dataset_name, X, s, _ = crime.process()
except FileExistsError as e:
    print(f"{e}; loading instead")
    dataset_name, X, s, _ = crime.load()

Loading the original Communities and Crime dataset from 'data/datasets/crime/_original/communities+and+crime.zip'
  shape: (1994, 128)
Processing the original Communities and Crime dataset
  Retaining only required attributes
    # non-sensitive attributes: 20
    sensitive attribute: 'racepctblack'
    shape: (1994, 21)
Exporting the processed Communities and Crime dataset (crime) to 'data/datasets/crime/crime.csv'
╭───────────┬─────────────┬──────────────┬─────────────────────────────┬───────────────────────╮
│   dataset │   # objects │   # features │   # nonsensitive attributes │   sensitive attribute │
├───────────┼─────────────┼──────────────┼─────────────────────────────┼───────────────────────┤
│     crime │        1994 │           20 │                          20 │          racepctblack │
╰───────────┴─────────────┴──────────────┴─────────────────────────────┴───────────────────────╯

#### Descriptive statistics of the non-sensitive attributes

In [13]:
X.apply(utils.describe_ser).T

                  min  max      mean       std % missing
attribute
pctWInvInc        0.0  1.0  0.495687  0.178071       0.0
pctWPubAsst       0.0  1.0  0.317778  0.222137       0.0
NumUnderPov       0.0  1.0  0.055507  0.127941       0.0
PctPopUnderPov    0.0  1.0  0.303024  0.228474       0.0
PctUnemployed     0.0  1.0  0.363531  0.202171       0.0
MalePctDivorce    0.0  1.0  0.461244   0.18246       0.0
FemalePctDiv      0.0  1.0  0.487568   0.17517       0.0
TotalPctDiv       0.0  1.0  0.494273  0.183607       0.0
PersPerFam        0.0  1.0  0.487748  0.154594       0.0
PctKids2Par       0.0  1.0  0.620657  0.206353       0.0
PctYoungKids2Par  0.0  1.0  0.664032  0.218749       0.0
PctTeen2Par       0.0  1.0  0.582884  0.191507       0.0
NumIlleg          0.0  1.0  0.036294  0.108671       0.0
PctIlleg          0.0  1.0  0.249995  0.229946       0.0
PctPersOwnOccup   0.0  1.0  0.562598  0.197087       0.0
HousVacant        0.0  1.0  0.076815  0.150465       0.0
PctHousOwnOcc     0.0  1.0  0.548686  0.185204       0.0
PctVacantBoarded  0.0  1.0  0.204529   0.21777       0.0
NumInShelters     0.0  1.0  0.029438  0.102607       0.0
NumStreet         0.0  1.0  0.022778    0.1004       0.0

#### Descriptive statistics of the sensitive attribute

In [14]:
utils.describe_ser(ser=s).to_frame().T

              min  max      mean       std % missing
racepctblack  0.0  1.0  0.179629  0.253442       0.0

## Motor Insurance

#### Download the original Motor Insurance dataset

In [15]:
motor.download()

Preparing to download the original Motor Insurance dataset
Downloading from 'http://freakonometrics.free.fr/pricing.csv'
Downloaded to 'data/datasets/motor/_original/pricing.csv'
Downloading from 'https://freakonometrics.hypotheses.org/files/2015/08/Pricing_ENG.pdf'
Downloaded to 'data/datasets/motor/_original/Pricing_ENG.pdf'

#### Process the original Motor Insurance dataset

In [16]:
try:
    dataset_name, X, s, _ = motor.process()
except FileExistsError as e:
    print(f"{e}; loading instead")
    dataset_name, X, s, _ = motor.load()

Loading the original Motor Insurance dataset from 'data/datasets/motor/_original/pricing.csv'
  shape: (36311, 15)
Processing the original Motor Insurance dataset
  Retaining only required attributes
    # non-sensitive attributes: 11
    sensitive attribute: 'Age'
    shape: (36311, 12)
  Standardising continuous non-sensitive attributes
  One hot encoding categorical non-sensitive attributes
    shape: (36311, 529)
  Dropping original categorical non-sensitive attributes
    shape: (36311, 522)
Exporting the processed Motor Insurance dataset (motor) to 'data/datasets/motor/motor.csv'
╭───────────┬─────────────┬──────────────┬─────────────────────────────┬───────────────────────╮
│   dataset │   # objects │   # features │   # nonsensitive attributes │   sensitive attribute │
├───────────┼─────────────┼──────────────┼─────────────────────────────┼───────────────────────┤
│     motor │       36311 │          521 │                          11 │                   Age │
╰───────────┴─────────────┴──────────────┴─────────────────────────────┴───────────────────────╯

#### Descriptive statistics of the non-sensitive attributes

In [17]:
X.apply(utils.describe_ser).T

                               min       max      mean       std % missing
Type:A                         0.0  0.707107  0.198709  0.317846       0.0
Type:B                         0.0  0.707107  0.158204  0.294688       0.0
Type:C                         0.0  0.707107  0.099238  0.245612       0.0
Type:D                         0.0  0.707107  0.135186  0.278061       0.0
Type:E                         0.0  0.707107  0.076785  0.220001       0.0
Type:F                         0.0  0.707107  0.038986  0.161395       0.0
Category:Large                 0.0  0.707107   0.24712  0.337157       0.0
Category:Medium                0.0  0.707107  0.260187  0.341007       0.0
Category:Small                 0.0  0.707107  0.199799  0.318375       0.0
Occupation:Employed            0.0  0.707107  0.221045  0.327787       0.0
Occupation:Housewife           0.0  0.707107  0.141476  0.282887       0.0
Occupation:Retired             0.0  0.707107  0.092948  0.238927       0.0
Occupation:Self-employed       0.0  0.707107  0.145351  0.285752       0.0
Occupation:Unemployed          0.0  0.707107  0.106287  0.252708       0.0
Group1:1                       0.0  0.707107  0.014566  0.100439       0.0
Group1:2                       0.0  0.707107  0.018831  0.113848       0.0
Group1:3                       0.0  0.707107  0.021402  0.121143       0.0
Group1:4                       0.0  0.707107  0.024868  0.130255       0.0
Group1:5                       0.0  0.707107  0.030359  0.143339       0.0
Group1:6                       0.0  0.707107  0.034507  0.152349       0.0
Group1:7                       0.0  0.707107  0.040758  0.164803       0.0
Group1:8                       0.0  0.707107  0.043796  0.170444       0.0
Group1:9                       0.0  0.707107  0.050047  0.181342       0.0
Group1:10                      0.0  0.707107  0.056532  0.191779       0.0
Group1:11                      0.0  0.707107  0.055149  0.189621       0.0
Group1:12                      0.0  0.707107  0.053338   0.18674       0.0
Group1:13                      0.0  0.707107  0.052579  0.185513       0.0
Group1:14                      0.0  0.707107  0.047243  0.176564       0.0
Group1:15                      0.0  0.707107  0.041849  0.166856       0.0
Group1:16                      0.0  0.707107  0.034741  0.152837       0.0
Group1:17                      0.0  0.707107  0.030009  0.142546       0.0
Group1:18                      0.0  0.707107  0.024264  0.128721       0.0
Group1:19                      0.0  0.707107  0.019006  0.114362       0.0
Group1:20                      0.0  0.707107  0.013262  0.095926       0.0
Bonus                     -0.88451  3.191023       0.0  1.000014       0.0
Poldur                    -1.20175  2.040769      -0.0  1.000014       0.0
Value                    -1.473497  3.179643       0.0  1.000014       0.0
Adind:0                        0.0  0.707107  0.340496  0.353317       0.0
Adind:1                        0.0  0.707107   0.36661  0.353317       0.0
SubGroup2:L1                   0.0  0.707107  0.001032  0.026996       0.0
SubGroup2:L10                  0.0  0.707107  0.001344  0.030795       0.0
SubGroup2:L100                 0.0  0.707107  0.001129  0.028238       0.0
SubGroup2:L101                 0.0  0.707107  0.001324  0.030572       0.0
SubGroup2:L102                 0.0  0.707107   0.00111  0.027994       0.0
SubGroup2:L103                 0.0  0.707107  0.001441  0.031889       0.0
SubGroup2:L104                 0.0  0.707107  0.000876  0.024878       0.0
SubGroup2:L105                 0.0  0.707107  0.000915  0.025424       0.0
SubGroup2:L106                 0.0  0.707107  0.001324  0.030572       0.0
SubGroup2:L107                 0.0  0.707107  0.001675  0.034372       0.0
SubGroup2:L108                 0.0  0.707107  0.001091  0.027748       0.0
SubGroup2:L109                 0.0  0.707107  0.001246  0.029661       0.0
SubGroup2:L11                  0.0  0.707107  0.001052  0.027249       0.0
SubGroup2:L110                 0.0  0.707107   0.00148  0.032316       0.0
SubGroup2:L111                 0.0  0.707107   0.00148  0.032316       0.0
SubGroup2:L112                 0.0  0.707107  0.000974  0.026222       0.0
SubGroup2:L113                 0.0  0.707107  0.001344  0.030795       0.0
SubGroup2:L114                 0.0  0.707107  0.001227  0.029428       0.0
SubGroup2:L115                 0.0  0.707107  0.001227  0.029428       0.0
SubGroup2:L116                 0.0  0.707107  0.001694  0.034571       0.0
SubGroup2:L117                 0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:L118                 0.0  0.707107  0.000759  0.023162       0.0
SubGroup2:L119                 0.0  0.707107  0.001344  0.030795       0.0
SubGroup2:L12                  0.0  0.707107   0.00111  0.027994       0.0
SubGroup2:L120                 0.0  0.707107  0.000876  0.024878       0.0
SubGroup2:L121                 0.0  0.707107  0.001519  0.032738       0.0
SubGroup2:L122                 0.0  0.707107  0.001324  0.030572       0.0
SubGroup2:L123                 0.0  0.707107  0.001168   0.02872       0.0
SubGroup2:L124                 0.0  0.707107  0.001344  0.030795       0.0
SubGroup2:L125                 0.0  0.707107  0.000643  0.021307       0.0
SubGroup2:L126                 0.0  0.707107  0.001305  0.030346       0.0
SubGroup2:L127                 0.0  0.707107  0.001207  0.029194       0.0
SubGroup2:L128                 0.0  0.707107  0.001266  0.029891       0.0
SubGroup2:L129                 0.0  0.707107  0.001188  0.028958       0.0
SubGroup2:L13                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L130                 0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:L131                 0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:L132                 0.0  0.707107  0.001071  0.027499       0.0
SubGroup2:L133                 0.0  0.707107  0.000993  0.026482       0.0
SubGroup2:L134                 0.0  0.707107  0.001168   0.02872       0.0
SubGroup2:L135                 0.0  0.707107  0.000993  0.026482       0.0
SubGroup2:L136                 0.0  0.707107  0.001032  0.026996       0.0
SubGroup2:L14                  0.0  0.707107  0.001499  0.032528       0.0
SubGroup2:L15                  0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:L16                  0.0  0.707107  0.001129  0.028238       0.0
SubGroup2:L17                  0.0  0.707107  0.001188  0.028958       0.0
SubGroup2:L18                  0.0  0.707107  0.001091  0.027748       0.0
SubGroup2:L19                  0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:L2                   0.0  0.707107  0.000837  0.024319       0.0
SubGroup2:L20                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L21                  0.0  0.707107  0.001207  0.029194       0.0
SubGroup2:L22                  0.0  0.707107  0.001013   0.02674       0.0
SubGroup2:L23                  0.0  0.707107  0.001013   0.02674       0.0
SubGroup2:L24                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L25                  0.0  0.707107  0.001344  0.030795       0.0
SubGroup2:L26                  0.0  0.707107  0.001422  0.031674       0.0
SubGroup2:L27                  0.0  0.707107  0.000915  0.025424       0.0
SubGroup2:L28                  0.0  0.707107   0.00111  0.027994       0.0
SubGroup2:L29                  0.0  0.707107  0.001441  0.031889       0.0
SubGroup2:L3                   0.0  0.707107  0.000935  0.025692       0.0
SubGroup2:L30                  0.0  0.707107  0.000935  0.025692       0.0
SubGroup2:L31                  0.0  0.707107  0.001071  0.027499       0.0
SubGroup2:L32                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L33                  0.0  0.707107  0.001305  0.030346       0.0
SubGroup2:L34                  0.0  0.707107  0.001227  0.029428       0.0
SubGroup2:L35                  0.0  0.707107  0.001324  0.030572       0.0
SubGroup2:L36                  0.0  0.707107  0.001344  0.030795       0.0
SubGroup2:L37                  0.0  0.707107  0.001383  0.031237       0.0
SubGroup2:L38                  0.0  0.707107  0.001266  0.029891       0.0
SubGroup2:L39                  0.0  0.707107  0.001188  0.028958       0.0
SubGroup2:L4                   0.0  0.707107  0.001188  0.028958       0.0
SubGroup2:L40                  0.0  0.707107  0.000954  0.025958       0.0
SubGroup2:L41                  0.0  0.707107  0.001266  0.029891       0.0
SubGroup2:L42                  0.0  0.707107  0.001305  0.030346       0.0
SubGroup2:L43                  0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:L44                  0.0  0.707107  0.001246  0.029661       0.0
SubGroup2:L45                  0.0  0.707107  0.001091  0.027748       0.0
SubGroup2:L46                  0.0  0.707107  0.001402  0.031456       0.0
SubGroup2:L47                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L48                  0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:L49                  0.0  0.707107  0.001324  0.030572       0.0
SubGroup2:L5                   0.0  0.707107  0.000896  0.025152       0.0
SubGroup2:L50                  0.0  0.707107  0.001499  0.032528       0.0
SubGroup2:L51                  0.0  0.707107  0.001071  0.027499       0.0
SubGroup2:L52                  0.0  0.707107  0.001558  0.033154       0.0
SubGroup2:L53                  0.0  0.707107  0.001207  0.029194       0.0
SubGroup2:L54                  0.0  0.707107  0.000876  0.024878       0.0
SubGroup2:L55                  0.0  0.707107  0.001422  0.031674       0.0
SubGroup2:L56                  0.0  0.707107  0.001383  0.031237       0.0
SubGroup2:L57                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L58                  0.0  0.707107  0.001266  0.029891       0.0
SubGroup2:L59                  0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:L6                   0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:L60                  0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:L61                  0.0  0.707107   0.00148  0.032316       0.0
SubGroup2:L62                  0.0  0.707107  0.001538  0.032947       0.0
SubGroup2:L63                  0.0  0.707107  0.001032  0.026996       0.0
SubGroup2:L64                  0.0  0.707107  0.001266  0.029891       0.0
SubGroup2:L65                  0.0  0.707107  0.001052  0.027249       0.0
SubGroup2:L66                  0.0  0.707107  0.000935  0.025692       0.0
SubGroup2:L67                  0.0  0.707107  0.001383  0.031237       0.0
SubGroup2:L68                  0.0  0.707107  0.001013   0.02674       0.0
SubGroup2:L69                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L7                   0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:L70                  0.0  0.707107  0.001188  0.028958       0.0
SubGroup2:L71                  0.0  0.707107  0.002084  0.038329       0.0
SubGroup2:L72                  0.0  0.707107  0.000857    0.0246       0.0
SubGroup2:L73                  0.0  0.707107  0.001266  0.029891       0.0
SubGroup2:L74                  0.0  0.707107  0.000993  0.026482       0.0
SubGroup2:L75                  0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:L76                  0.0  0.707107  0.001129  0.028238       0.0
SubGroup2:L77                  0.0  0.707107  0.001577   0.03336       0.0
SubGroup2:L78                  0.0  0.707107  0.001636  0.033971       0.0
SubGroup2:L79                  0.0  0.707107  0.001577   0.03336       0.0
SubGroup2:L8                   0.0  0.707107  0.001344  0.030795       0.0
SubGroup2:L80                  0.0  0.707107  0.000798  0.023748       0.0
SubGroup2:L81                  0.0  0.707107  0.001363  0.031017       0.0
SubGroup2:L82                  0.0  0.707107  0.001383  0.031237       0.0
SubGroup2:L83                  0.0  0.707107  0.001188  0.028958       0.0
SubGroup2:L84                  0.0  0.707107  0.001597  0.033565       0.0
SubGroup2:L85                  0.0  0.707107  0.001227  0.029428       0.0
SubGroup2:L86                  0.0  0.707107  0.001091  0.027748       0.0
SubGroup2:L87                  0.0  0.707107  0.001577   0.03336       0.0
SubGroup2:L88                  0.0  0.707107  0.001324  0.030572       0.0
SubGroup2:L89                  0.0  0.707107  0.001227  0.029428       0.0
SubGroup2:L9                   0.0  0.707107  0.000993  0.026482       0.0
SubGroup2:L90                  0.0  0.707107  0.001558  0.033154       0.0
SubGroup2:L91                  0.0  0.707107  0.001772  0.035355       0.0
SubGroup2:L92                  0.0  0.707107  0.001168   0.02872       0.0
SubGroup2:L93                  0.0  0.707107  0.001052  0.027249       0.0
SubGroup2:L94                  0.0  0.707107  0.001383  0.031237       0.0
SubGroup2:L95                  0.0  0.707107  0.001305  0.030346       0.0
SubGroup2:L96                  0.0  0.707107  0.001207  0.029194       0.0
SubGroup2:L97                  0.0  0.707107  0.001168   0.02872       0.0
SubGroup2:L98                  0.0  0.707107  0.001441  0.031889       0.0
SubGroup2:L99                  0.0  0.707107  0.001499  0.032528       0.0
SubGroup2:M1                   0.0  0.707107  0.002298  0.040244       0.0
SubGroup2:M10                  0.0  0.707107  0.001655  0.034172       0.0
SubGroup2:M11                  0.0  0.707107  0.002726  0.043822       0.0
SubGroup2:M12                  0.0  0.707107  0.002707  0.043666       0.0
SubGroup2:M13                  0.0  0.707107  0.002337  0.040583       0.0
SubGroup2:M14                  0.0  0.707107  0.002629  0.043036       0.0
SubGroup2:M15                  0.0  0.707107  0.002395  0.041085       0.0
SubGroup2:M16                  0.0  0.707107  0.002006  0.037607       0.0
SubGroup2:M17                  0.0  0.707107   0.00296  0.045654       0.0
SubGroup2:M18                  0.0  0.707107  0.002045   0.03797       0.0
SubGroup2:M19                  0.0  0.707107  0.002687   0.04351       0.0
SubGroup2:M2                   0.0  0.707107  0.001908  0.036686       0.0
SubGroup2:M20                  0.0  0.707107  0.002454  0.041582       0.0
SubGroup2:M21                  0.0  0.707107  0.002025  0.037789       0.0
SubGroup2:M22                  0.0  0.707107  0.002668  0.043352       0.0
SubGroup2:M3                   0.0  0.707107  0.002493  0.041909       0.0
SubGroup2:M4                   0.0  0.707107  0.002765  0.044133       0.0
SubGroup2:M5                   0.0  0.707107  0.002512  0.042072       0.0
SubGroup2:M6                   0.0  0.707107  0.002201  0.039385       0.0
SubGroup2:M7                   0.0  0.707107  0.002609  0.042877       0.0
SubGroup2:M8                   0.0  0.707107  0.002317  0.040414       0.0
SubGroup2:M9                   0.0  0.707107  0.002142  0.038861       0.0
SubGroup2:N1                   0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:N10                  0.0  0.707107  0.001636  0.033971       0.0
SubGroup2:N11                  0.0  0.707107  0.001441  0.031889       0.0
SubGroup2:N12                  0.0  0.707107  0.001908  0.036686       0.0
SubGroup2:N13                  0.0  0.707107  0.001558  0.033154       0.0
SubGroup2:N14                  0.0  0.707107  0.001246  0.029661       0.0
SubGroup2:N15                  0.0  0.707107  0.001636  0.033971       0.0
SubGroup2:N16                  0.0  0.707107  0.000896  0.025152       0.0
SubGroup2:N17                  0.0  0.707107  0.001869  0.036311       0.0
SubGroup2:N18                  0.0  0.707107  0.001558  0.033154       0.0
SubGroup2:N19                  0.0  0.707107  0.000876  0.024878       0.0
SubGroup2:N2                   0.0  0.707107  0.001266  0.029891       0.0
SubGroup2:N20                  0.0  0.707107  0.001168   0.02872       0.0
SubGroup2:N21                  0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:N22                  0.0  0.707107  0.001753   0.03516       0.0
SubGroup2:N23                  0.0  0.707107  0.001227  0.029428       0.0
SubGroup2:N24                  0.0  0.707107  0.000993  0.026482       0.0
SubGroup2:N25                  0.0  0.707107  0.000954  0.025958       0.0
SubGroup2:N26                  0.0  0.707107  0.000935  0.025692       0.0
SubGroup2:N3                   0.0  0.707107  0.001168   0.02872       0.0
SubGroup2:N4                   0.0  0.707107  0.001655  0.034172       0.0
SubGroup2:N5                   0.0  0.707107  0.000876  0.024878       0.0
SubGroup2:N6                   0.0  0.707107  0.001675  0.034372       0.0
SubGroup2:N7                   0.0  0.707107  0.001441  0.031889       0.0
SubGroup2:N8                   0.0  0.707107  0.001792  0.035548       0.0
SubGroup2:N9                   0.0  0.707107  0.002181  0.039211       0.0
SubGroup2:O1                   0.0  0.707107  0.001227  0.029428       0.0
SubGroup2:O10                  0.0  0.707107   0.00074  0.022863       0.0
SubGroup2:O11                  0.0  0.707107   0.00148  0.032316       0.0
SubGroup2:O12                  0.0  0.707107  0.001324  0.030572       0.0
SubGroup2:O13                  0.0  0.707107  0.000837  0.024319       0.0
SubGroup2:O14                  0.0  0.707107  0.001032  0.026996       0.0
SubGroup2:O15                  0.0  0.707107  0.000993  0.026482       0.0
SubGroup2:O16                  0.0  0.707107  0.001032  0.026996       0.0
SubGroup2:O17                  0.0  0.707107  0.000954  0.025958       0.0
SubGroup2:O18                  0.0  0.707107   0.00074  0.022863       0.0
SubGroup2:O19                  0.0  0.707107  0.001052  0.027249       0.0
SubGroup2:O2                   0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:O20                  0.0  0.707107  0.000954  0.025958       0.0
SubGroup2:O21                  0.0  0.707107  0.001149   0.02848       0.0
SubGroup2:O22                  0.0  0.707107  0.000954  0.025958       0.0
SubGroup2:O23                  0.0  0.707107  0.000857    0.0246       0.0
SubGroup2:O24                  0.0  0.707107  0.000876  0.024878       0.0
SubGroup2:O25                  0.0  0.707107  0.001188  0.028958       0.0
SubGroup2:O26                  0.0  0.707107  0.001207  0.029194       0.0
SubGroup2:O27                  0.0  0.707107  0.000915  0.025424       0.0
SubGroup2:O28                  0.0  0.707107  0.000798  0.023748       0.0
SubGroup2:O29                  0.0  0.707107  0.001129  0.028238       0.0
SubGroup2:O3                   0.0  0.707107  0.000974  0.026222       0.0
SubGroup2:O30                  0.0  0.707107  0.001052  0.027249       0.0
SubGroup2:O31                  0.0  0.707107  0.001071  0.027499       0.0
SubGroup2:O32                  0.0  0.707107  0.000915  0.025424       0.0
SubGroup2:O33                  0.0  0.707107  0.000798  0.023748       0.0
SubGroup2:O34                  0.0  0.707107   0.00111  0.027994       0.0
SubGroup2:O35                  0.0  0.707107  0.000701  0.022254       0.0
SubGroup2:O36                  0.0  0.707107  0.000662  0.021628       0.0
SubGroup2:O37                  0.0  0.707107  0.000857    0.0246       0.0
SubGroup2:O38                  0.0  0.707107  0.001071  0.027499       0.0
SubGroup2:O39                  0.0  0.707107  0.000837  0.024319       0.0
SubGroup2:O4                   0.0  0.707107  0.000876  0.024878       0.0
SubGroup2:O5                   0.0  0.707107  0.001032  0.026996       0.0
SubGroup2:O6                   0.0  0.707107  0.000896  0.025152       0.0
SubGroup2:O7                   0.0  0.707107  0.000857    0.0246       0.0
SubGroup2:O8                   0.0  0.707107   0.00074  0.022863       0.0
SubGroup2:O9                   0.0  0.707107  0.000798  0.023748       0.0
SubGroup2:P1                   0.0  0.707107  0.001013   0.02674       0.0
SubGroup2:P10                  0.0  0.707107  0.001285   0.03012       0.0
SubGroup2:P11                  0.0  0.707107  0.000974  0.026222       0.0

#### Descriptive statistics of the sensitive attribute

In [18]:
utils.describe_ser(ser=s).to_frame().T

    min max       mean        std % missing
Age  18  75  41.186087  14.306933       0.0